# Generated by Django 5.1.3 on 2024-12-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='message',
            new_name='text',
        ),
    ]
