# Generated by Django 5.1.3 on 2024-12-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_message_register_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='text',
        ),
    ]
