# Generated by Django 5.1.3 on 2024-12-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_number',
            new_name='order_name',
        ),
    ]
